### ISSUE TITLE
Windows binaries 32/64 bit for Seahorse

### ISSUE THREAD

**Issue by ChessGUI** [cordescodes/SeahorseChessEngine#1]
Hello swcordes,

can you please build Windows binaries 32/64 bit for Seahorse and host these files on your website, too?

By the way: Jérémy Pages from France created some years ago a WinBoard-compatible chess engine
"Hippocampe" http://www.computer-chess.org/lib/exe/fetch.php?media=computer_chess:wiki:download:hippocampe-0.4.2.tar.gz
(hippocampe is the French notion of seahorse)

**Comment by cordescodes** [comment]
Hi ChessGUI,

I have added a 64-bit Windows binary. And I had never heard of the chess engine Hippocampe. Thanks for letting me know! Please let me know if you have any issues with the binary. I've been able to use it with Arena.

Thanks for your interest in Seahorse!

Sam

**Comment by cordescodes** [comment]
I mistakenly classified the executable as 64-bit when it is in fact 32-bit. My apologies for the confusion.
