### ISSUE TITLE
missing libgcc_s_dw2-1.dll-file for Windows 7 SP1 x64

### ISSUE THREAD

**Issue by ChessGUI** [cordescodes/SeahorseChessEngine#2]
Hello swcordes,

Seahorse is a little bit stubborn, it requires http://de.originaldll.com/file/libgcc_s_dw2-1.dll/29940.html additionally; just download the extracted version (>blue button above) from this mentioned website. 
By the way: ChessGUI that is my nick supports UCI 1/2 and WB1/2-protocols too http://www.chess.hylogic.de/
A survey of other interfaces is here:
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list

**Comment by cordescodes** [comment]
Thanks for the information and links! I will definitely look into that.

Sam
