### ISSUE TITLE
Problems with compiling

### ISSUE THREAD

**Issue by archtux** [cordescodes/SeahorseChessEngine#3]
Hi Sam,

I'm trying to compile Seahorse for Linux but I can't due to 2 missing header files.(perft.h and hashmap.h)
Googling I couldn't find any information.
Where can I obtain those header files?

**Comment by cordescodes** [comment]
Hi archtux,

My apologies. perft.h and hashmap.h were header files I created for testing but which are not required to run Seahorse. I thought I had removed all references to them but embarrassingly had not.

I just pushed the updated files which have no dependencies on those header files. I'm sorry for the confusion. Please let me know if you have any other questions and thanks for your interest in Seahorse!

Sam
